### List all onboarding
GET http://localhost/bb-melhor-envio/wp-json/commerce/v1/onboarding

### Create an onboarding
POST http://localhost/bb-melhor-envio/wp-json/commerce/v1/onboarding
content-type: application/json

{
    "fullname": 1,
    "email": "john.doe@gmail.com!",
    "consent_newsletter": true,
    "consent_terms": true,
    "consent_privacy": true,
    "installation_id": "123456789",
    "site_language": "Portoguese",
    "timezone": "America/Sao_Paulo"
}

###
POST http://localhost/bb-melhor-envio/wp-json/commerce/v1/onboarding/2
content-type: application/json

{
    "fullname": "Pippolo"
}